### ISSUE TITLE
Allow for custom templates for generated output

### ISSUE THREAD

**Issue by Sircular** [azag0/knitj#5]
It would be very convenient if alternative Jinja templates could be used in place of the provided one. A command-line switch for easy access would be ideal.

**Comment by azag0** [comment]
Good point. I've added support for [YAML front matter](https://jekyllrb.com/docs/front-matter/). The template can be specified with a `template` option.

Markdown:
```markdown
---
template: myindex.html
---
```

Python:
```python
# ---
# template: myindex.html
# ---
```

Released in version 0.3.0.
